plugins {
    id('java')
}

group = 'com.lambdatest.sample'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    // Karate JUnit 5 runner
    testImplementation 'com.intuit.karate:karate-junit5:1.4.1'

    // JUnit 5 API and Engine
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.10.2'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.10.2'

    // (Optional but helps with error clarity)
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher:1.10.2'
}

test {
    useJUnitPlatform()
    maxParallelForks = 4
    // pull karate options into the runtime
    systemProperty "karate.options", System.getProperty("karate.options")
    // ensure tests are always run
    outputs.upToDateWhen { false }
}
