plugins {
    id('java')
}

group = 'com.lambdatest.sample'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    // https://mvnrepository.com/artifact/com.intuit.karate/karate-junit5
    // Karate JUnit5 runner
    testImplementation 'com.intuit.karate:karate-junit5:1.4.1'

    // Add JUnit 5 Jupiter API + engine
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.10.2'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.10.2'
}

test {
    useJUnitPlatform()
    maxParallelForks = 4
    // pull karate options into the runtime
    systemProperty "karate.options", System.getProperty("karate.options")
    // ensure tests are always run
    outputs.upToDateWhen { false }
}
